version: '3'

services:
  entrypoint:
    container_name: entrypoint
    env_file:
      - entrypoint/.env
    restart: always
    build: entrypoint/.
    ports:
      - "80:80"
    environment:
      - API_GATEWAY_BASE_URL=http://api_gateway:4000
      - SERVER_UPLOADS_DIRECTORY=../uploads

  api_gateway:
    container_name: api_gateway
    env_file:
      - api_gateway/.env
    restart: always
    build: api_gateway/.
    environment:
      - BOOK_MICROSERVICE_HOST=book_service
      - BOOK_MICROSERVICE_PORT=3000

  book_service:
    container_name: book_service
    env_file:
      - book_microservice/.env
    restart: always
    build: book_microservice/.
    links:
      - mongo
    environment:
      - DB_HOST=mongo

  user_service:
    container_name: user_service
    env_file:
      - user_microservice/.env
    restart: always
    build: user_microservice/.
    links:
      - mongo
    environment:
      - DB_HOST=mongo

  mongo:
    container_name: mongo
    image: mongo:latest
