version: '3'

services:
  entrypoint:
    container_name: entrypoint
    env_file:
      - entrypoint/.env
    restart: always
    build: entrypoint/.
    ports:
      - "80:80"
    environment:
      - API_GATEWAY_BASE_URL=http://api_gateway:4000
      - SERVER_UPLOADS_DIRECTORY=uploads

  api_gateway:
    container_name: api_gateway
    env_file:
      - api_gateway/.env
    restart: always
    build: api_gateway/.
    environment:
      - BOOK_MICROSERVICE_BASE_URL=http://book_service:3000
      - USER_MICROSERVICE_BASE_URL=http://user_service:3001

  book_service:
    container_name: book_service
    env_file:
      - book_microservice/.env
    restart: always
    build: book_microservice/.
    links:
      - db_mongo_books
    environment:
      - DB_HOST=db_mongo_books
      - DB_NAME=db_books

  user_service:
    container_name: user_service
    env_file:
      - user_microservice/.env
    restart: always
    build: user_microservice/.
    links:
      - db_mongo_users
    environment:
      - DB_HOST=db_mongo_users
      - DB_NAME=db_users

  db_mongo_books:
    container_name: db_mongo_books
    image: mongo:latest
    ports:
      - "27017:27017"

  db_mongo_users:
    container_name: db_mongo_users
    image: mongo:latest
    ports:
      - "27018:27017"
